2022-04-19 12:27:48.330359: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-19 12:27:48.330425: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[32m[04/19 12:28:13 valid-selec]: [0mFull config saved to /data3/wuyinjun/valid_set_selections/mnist_1//rand_error_0.6_valid_select_seq_select_0_all_layer_2/config.json
[32m[04/19 12:28:13 valid-selec]: [0mstart
[32m[04/19 12:28:13 valid-selec]: [0m==> Preparing data..
[32m[04/19 12:28:17 valid-selec]: [0m==> Loading cached model...
[32m[04/19 12:28:17 valid-selec]: [0m==> Loading cached model successfully
[32m[04/19 12:28:18 valid-selec]: [0msample batch ids::0
[32m[04/19 12:28:24 valid-selec]: [0msample batch ids::1
[32m[04/19 12:28:30 valid-selec]: [0msample batch ids::2
[32m[04/19 12:28:37 valid-selec]: [0msample batch ids::3
[32m[04/19 12:28:44 valid-selec]: [0msample batch ids::4
[32m[04/19 12:28:51 valid-selec]: [0msample batch ids::5
[32m[04/19 12:28:58 valid-selec]: [0msample batch ids::6
[32m[04/19 12:29:06 valid-selec]: [0msample batch ids::7
[32m[04/19 12:29:13 valid-selec]: [0msample batch ids::8
[32m[04/19 12:29:20 valid-selec]: [0msample batch ids::9
[32m[04/19 12:29:27 valid-selec]: [0msample batch ids::10
[32m[04/19 12:29:34 valid-selec]: [0msample batch ids::11
[32m[04/19 12:29:40 valid-selec]: [0msample batch ids::12
[32m[04/19 12:29:46 valid-selec]: [0msample batch ids::13
[32m[04/19 12:29:53 valid-selec]: [0msample batch ids::14
running k-means on cuda..
Traceback (most recent call last):
  File "/home/wuyinjun/validation_set_selection/src/main/main_train.py", line 1181, in <module>
    main2(args, logger)
  File "/home/wuyinjun/validation_set_selection/src/main/main_train.py", line 924, in main2
    cached_sample_weights=cached_sample_weights,
  File "/home/wuyinjun/validation_set_selection/src/datasets/dataloader.py", line 898, in get_dataloader_for_meta
    trainset, metaset, remaining_origin_labels = find_representative_samples0(criterion, optimizer, pretrained_model, trainset, None, args, origin_labels, cached_sample_weights = cached_sample_weights)
  File "/home/wuyinjun/validation_set_selection/src/datasets/dataloader.py", line 487, in find_representative_samples0
    valid_ids, new_valid_representations = get_representative_valid_ids2(criterion, optimizer, trainloader, args, net, valid_count, cached_sample_weights = cached_sample_weights)
  File "/home/wuyinjun/validation_set_selection/src/main/find_valid_set.py", line 471, in get_representative_valid_ids2
    valid_ids, valid_sample_representation_tensor = cluster_per_class(full_sample_representation_tensor, all_sample_ids, valid_count_per_class = main_represent_count, num_clusters = main_represent_count, sample_weights=None, cosin_distance=args.cosin_dist, is_cuda=args.cuda, all_layer=args.all_layer)  
  File "/home/wuyinjun/validation_set_selection/src/main/find_valid_set.py", line 67, in cluster_per_class
    X=sample_representation_vec_ls, num_clusters=num_clusters, distance='cosine', is_cuda=is_cuda, sample_weights=sample_weights, existing_cluster_mean_ls=existing_cluster_centroids, all_layer=all_layer)
  File "/home/wuyinjun/validation_set_selection/src/clustering_method/k_means.py", line 383, in kmeans_cosin
    full_x_cosin_sim = pairwise_cosine_full(X, is_cuda=is_cuda)
  File "/home/wuyinjun/validation_set_selection/src/clustering_method/k_means.py", line 641, in pairwise_cosine_full
    curr_B = curr_B.cuda()
RuntimeError: CUDA out of memory. Tried to allocate 41.13 GiB (GPU 0; 10.76 GiB total capacity; 181.41 MiB already allocated; 9.41 GiB free; 182.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
